# Generated by Django 4.0.3 on 2022-03-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_managers_remove_client_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_joined',
        ),
    ]
