# Generated by Django 4.0.3 on 2022-03-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_client_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
