# Generated by Django 4.0.3 on 2022-03-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalog',
            new_name='Disk',
        ),
    ]
