# Generated by Django 4.0.3 on 2022-03-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_catalog_disk'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
