# Generated by Django 4.0.3 on 2022-03-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_disk_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
    ]
