# Generated by Django 4.0.3 on 2022-03-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_disk_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disk',
            name='reserved',
        ),
    ]
