# Generated by Django 4.0.3 on 2022-03-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('catalog', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('style', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
