# Generated by Django 4.0.3 on 2022-03-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_managers_remove_client_is_staff_and_more'),
        ('order', '0002_remove_order_catalog_remove_order_release_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
