# Generated by Django 4.0.3 on 2022-03-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_disk_reserved'),
        ('client', '0007_client_phone'),
        ('order', '0003_alter_order_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.disk')),
            ],
        ),
    ]
